config/routes.rb
Rails.application.routes.draw do

  resources :infopopups
  resources :metrics
  resources :quarters
  resources :projects
  resources :agendas
  resources :userroles
  resources :actiontypes
  resources :mediators
  resources :mediations
  resources :participations
  resources :managers
  resources :assignments
  resources :roles

  #match 'users_admin/', to: 'users#create', via: :post, as: 'admin_create_user'

  #post 'admin_password_reset', to: 'users#password_reset', as: 'admin_password_reset'
  match '/users_password_reset', to: 'users#password_reset', via: :patch, as: 'admin_password_reset'

  resources :scopes
  resources :memberships
  resources :userroles
  resources :people
  resources :actiontypes
  resources :issueactions
  resources :actions
  resources :communities
  resources :appissues do
    collection { post :uploadcsv }
  end
  resources :structuretypes
  resources :statuses
  resources :categories
  resources :issues

  resources :organizations
  resources :meetings
  resources :counties
  resources :structures
  resources :districts



  #resources :searches

  resources :site_images
  resources :site_documents

  #devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_for :users
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  resources :posts
  resources  :people_structures
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  get 'resetpassword', :to => 'users#newpassword', as: 'resetpassword'
  get 'projectdashboard', :to => 'projects#dashboard', as: 'projectdashboard'
  get 'quarterlyreport', :to => 'projects#quarterlyreport', as: 'quarterlyreport'
  get 'structurereport', :to => 'projects#structurereport', as: 'structurereport'
  get 'projectlofa', :to => 'projects#lofa', as: 'projectlofa'
  get 'projectgrandgedeh', :to => 'projects#grandgedeh', as: 'projectgrandgedeh'
  get 'projectbong', :to => 'projects#bong', as: 'projectbong'
  get 'projectnimba', :to => 'projects#nimba', as: 'projectnimba'
  get 'managersmap', :to => 'structures#managersmap', as: 'managersmap'


  post 'addtoagenda', to: 'issuesactions#create_meetingagenda', as: 'addtoagenda'

  get 'resolution', to: 'issues#resolution', as: 'resolution'

  post 'addnote', to: 'issues#addnote', as: 'addnote'
  post 'addperson', to: 'structures#addperson', as: 'addperson'
  get 'adjustroles', to: 'users#adjustroles', as: 'adjustroles'
  get 'actionreport', to: 'visitors#actionreport', as: 'actionreport'
  get 'qtrreport', to: 'projects#qtrreport', as: 'qtrreport'
  get 'searchissues', to: 'issues#searchissues', as: 'searchissues'
  get 'issueresults', to: 'issues#searchresults', as: 'issueresults'
  get 'fixissue', to: 'appissues#fixissues', as: 'fixissues'

  get 'searchbyqtr', to: 'issues#searchbyqtr', as: 'searchbyqtr'
  get 'searchbyqtrresults', to: 'issues#searchbyqtrresults', as: 'searchbyqtrresults'
  get 'searchmeetings', to: 'meetings#searchmeetings', as: 'searchmeetings'
  
  get 'meetingresults', to: 'meetings#meetingresults', as: 'meetingresults'
  
  get 'monthlyreport', to: 'projects#monthlyreport', as: 'monthlyreport'
  get 'monthlyresults', to: 'projects#monthlyresults', as: 'monthlyresults'

  get 'qprreport', to: 'projects#qprreport', as: 'qprreport'
  get 'qprresults', to: 'projects#qprresults', as: 'qprresults'


  get 'countyadminreport', to: 'projects#countyadminreport', as: 'countyadminreport'
  get 'countyadminresults', to: 'projects#countyadminresults', as: 'countyadminresults'

  get 'newmldluser', to: 'users#newmldluser', as: 'newmldluser'
  post 'createuser', to: 'users#createuser', as: 'createuser'
  get 'deletemanager', to: 'structures#deletemanager', as: 'deletemanager'
  get 'deletemediator', to: 'mediations#deletemediator', as: 'deletemediator'
  get 'deletemembership', to: 'structures#deletemembership', as: 'deletemembership'
  get 'deleteparticipation', to: 'meetings#deleteparticipation', as: 'deleteparticipation'
  get 'deletedisputant', to: 'issues#deletedisputant', as: 'deletedisputant'
  get 'deletecommitteemember', to: 'issues#deletecommitteemember', as: 'deletecommitteemember'

  get 'meettemplate', to: 'meetings#blankmeeting', as: 'meettemplate'
  get 'othercategories', to: 'projects#othercategories', as: 'othercategories'
  get 'resultaudit', to: 'projects#resultaudit', as: 'resultaudit'
  post 'adddisputant', to: 'issues#adddisputant', as: 'adddisputant'
  post 'addcommitteemember', to: 'issues#addcommitteemember', as: 'addcommitteemember'
  post 'addparticipant', to: 'meetings#addparticipant', as: 'addparticipant'
  post 'addmediator', to: 'mediations#addmediator', as: 'addmediator'
  post 'addmemember', to: 'structures#addmembership', as: 'addmember'
  post 'addmanager', to: 'structures#addmanager', as: 'addmanager'
  get 'seedpeeps', to: 'people#seedpeeps', as: 'seedpeeps'
  get 'datacsv', to: 'issues#dumpfile', as: 'datacsv'
  get 'issuedump', to: 'issues#issuedump', as: 'issuedump'
  get 'structureissuedump', to: 'structures#structureissuedump', as: 'structureissuedump'

  get 'meetingcheck', to: 'meetings#meetingchecker', as: 'meetingcheck'
  get 'basicdata', to: 'projects#basicdatasetup', as: 'basicdata'
  get 'basictableoutput', to: 'projects#basictableoutput', as: 'basictableoutput'
  get 'downloadissues', to: 'issues#action_name', as: 'downloadissues'
  get 'seeder', to: 'issues#seeder', as: 'seeder'
  get 'clearsteve', to: 'projects#clearsteve', as: 'clearsteve'
  get '/tests2', :to => redirect('/tests2.html')
  root 'visitors#index'
  #get "counties/:county_id/districts", to: "application#districts", as: "districts", format: :json



end

app/models/mediation.rb
class Mediation < ActiveRecord::Base
  validates :mediate_start, presence: true

  belongs_to :issue


  has_many :mediatior, :dependent => :destroy
  has_many :people, :through => :mediatiors
  has_many :issueactions, :dependent => :destroy


  extend EnumerateIt
  has_enumeration_for :result, create_helpers: true

  def mediationcode()
    issue = self.issue

    id= ('MED-' + self.id.to_s + '-' + self.issue.issuecode)
    return id
  end



  def status
    if self.mediation_held
      sname = 'Closed'
    else
      sname = 'Open'
    end
  end

end

app/controllers/mediations_controller.rb
class MediationsController < ApplicationController
  before_action :set_mediation, only: [:show, :edit, :update, :destroy]

  # GET /mediations
  # GET /mediations.json
  def index
    @mediations = Mediation.all
  end

  # GET /mediations/1
  # GET /mediations/1.json
  def show
    @issue=Issue.find(@mediation.issue_id)
    if @issue.structure.ismanager(current_user.id) or current_user.mldlrole == 1
      @canedit=true
    end
    #@issue=Issue.find(@mediation.issue_id)
    @mediators = Mediator.where('mediation_id = ?', @mediation.id)
    @mediator = Mediator.new
    @new_site_document = SiteDocument.new
    @issueaction = Issueaction.new
    @available_people = Person.all
    @mediationdocs = SiteDocument.where('documentable_type = ? and documentable_id = ?', 'mediation', @mediation.id)
  end

  # GET /mediations/new
  def new
    @mediation = Mediation.new
    if params[:issue_id]

      @issue = Issue.find(params[:issue_id])

    end
  end

  # GET /mediations/1/edit
  def edit
  end

  # POST /mediations
  # POST /mediations.json
  def create

    @mediation = Mediation.new(mediation_params)

    d1 = Date.parse(params[:mediate_start])


    @mediation.mediation_start = d1



    issueaction= Issueaction.new
    issue = Issue.find(@mediation.issue_id)

    Issueaction.create(mediation_id: @mediation.id, issue_id: params[:issue_id], user_id: current_user.id, actiontype: Actiontype::MEDIATION, structure_id: issue.structure_id)
    respond_to do |format|
      if @mediation.save

        format.html { redirect_to issue, notice: 'Mediation was successfully created.' }
        format.json { render :show, status: :created, location: @mediation }
      else
        format.html { render :new }
        format.json { render json: @mediation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mediations/1
  # PATCH/PUT /mediations/1.json
  def update
   # if !params[:mediate_start].blank?
      #d1 = Date.parse(params[:mediate_start])
      #@mediation.update_attributes!(:mediation_start => d1)
    #end
    #if !params[:mediate_end].blank?
    #  d2 = Date.parse(params[:mediate_end])
    #  @mediation.update_attributes!(:mediation_end => d2)
    #end
    #Issueaction.create(mediation_id: @mediation.id, issue_id: params[[:issue_id], user_id: current_user.id, actiontype: params[:actiontype], structure_id: issue.structure_id)

    #@mediation.update_attributes!(:mediation_end => d2)
    respond_to do |format|
      if @mediation.update(mediation_params)
        Userlog.create(user_id: current_user.id, loggable_type: 'Mediation', loggable_id: @mediation.id, action: 'Update')
        format.html { redirect_to @mediation, notice: 'Mediation was successfully updated.' }
        format.json { render :show, status: :ok, location: @mediation }
      else
        format.html { render :edit }
        format.json { render json: @mediation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mediations/1
  # DELETE /mediations/1.json
  def destroy
    @mediation.destroy
    respond_to do |format|
      format.html { redirect_to mediations_url, notice: 'Mediation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  def addmediator
    @mediator = Mediator.new
    mediation=Mediation.find(params[:mediation_id])
    @mediator.mediation_id = mediation.id
    if params[:addpeep]
      peep=Person.create(name_first: params[:fname], name_last: params[:lname], email: params[:email], title: params[:title], organization_id: params[:organization_id])
      @mediator.person_id = peep.id
    else
      @mediator.person_id = params[:person_id]
    end

    respond_to do |format|
      if @mediator.save
        format.html { redirect_to mediation, notice: 'Mediator assigned to Mediation.' }
        format.json { render :show, status: :created, location: @mediator }
      else
        format.html { render :new }
        format.json { render json: @mediator.errors, status: :unprocessable_entity }
      end
    end

  end


  def deletemediator
    p=Mediator.find(params[:mediator_id]).destroy
    m = Mediation.find(p.mediation_id)
    respond_to do |format|
      format.html { redirect_to m, notice: 'Mediator has been removed.' }
      format.json { head :no_content }
    end
  end
















  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mediation
      @mediation = Mediation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mediation_params
      params.require(:mediation).permit(:name, :issue_id, :mediate_start, :mediate_end, :mediation_held, :mediation_notes)
    end
end

app/helpers/mediations_helper.rb
module MediationsHelper
end

app/views/mediations/_addmediator.html.erb
<%= form_tag addmediator_path do %>

    <%= render 'people/addpeopletoobject' %>

    <%= hidden_field_tag(:mediation_id, @mediation.id) %>
    <div class="actions">
      <%= submit_tag 'Submit', :class => "btn btn-small btn-primary" %>
    </div>
<% end %>

app/views/mediations/_form.html.erb
<div class="panel panel-default">

    <div class="panel-heading">
        <%if params[:action] == "edit" %><h3><strong><%= @mediation.mediationcode %></strong></h3><% end %>
    </div>

    <div class="panel-body">
          <%= form_for @mediation do |f| %>


            <% if params[:issue_id] %>
                <%= hidden_field(:mediation, :issue_id, :value => params[:issue_id]) %>
            <% else %>
                <%= hidden_field(:mediation, :issue_id, :value => @mediation.issue_id) %>

            <% end %>

            <% if @mediation.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@mediation.errors.count, "error") %> prohibited this mediation from being saved:</h2>

                    <ul>
                    <% @mediation.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>


            <div class="field">
                <%= f.label :mediate_start %><br>
              <%= f.text_field :mediate_start, :id => "datepicker-example1" %>


            </div>
          <div class="field">
            <%= f.label :mediate_end %><br>
            <%= f.text_field :mediate_end, :id => "datepicker-example2" %>


          </div>



            <div class="field">
                <%= f.label :mediation_notes %><br>

                <%= f.text_area :mediation_notes, cols: "120", rows: "12" %>
             </div>
            <div class="actions">
                <%= f.submit :class => 'btn btn-primary' %>
            </div>
        <% end %>
    </div>

</div>

<script type="text/javascript">
    $('#datepicker-example1').Zebra_DatePicker();
</script>

  <script type="text/javascript">
      $('#datepicker-example2').Zebra_DatePicker();
  </script>

app/views/mediations/_mediationresults.html.erb
<style>

    .actionbox {
        border: 1px solid #ccc;
        padding: 10px;
    }
    .radioin {
        font-size: 16px;
    }
    .notefield {
        width: 100%;
    }


    #send_to_one{display:none;}
</style>


<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@issueaction, html: {role: :form, 'data-model' => 'issueaction', id: 'mediationresult'}) do |f| %>
    <%#= form_for (@agenda), html: {id: "meetingresult"} do |f| %>
    <%= hidden_field(:issueaction, :issue_id, :value => @mediation.issue_id) %>
    <%= hidden_field(:issueaction, :structure_id, :value => @mediation.issue.structure_id) %>
    <%= hidden_field_tag(:frommediation, true) %>
    <%= hidden_field(:issueaction, :mediation_id, :value => @mediation.id) %>

<%# Added Bootstrap classes, and help-block container for error messages %>



    <div class="row">
      <div class="col-sm-12 actionbox">


        <div class="col-sm-3 radioin">
          <%= radio_button(:issueaction, 'actiontype', Actiontype::RESOLVED, id: "checkresolve") %> Resolved<br>

        </div>
        <div class="col-sm-9">
          <strong>Resolution Date</strong><br>
          <div id="sandbox-container">
            <div class="input-group date">
              <input  name="resolution_date" type="text" id="resolution_date" class="form-control" width="100">
              <%# f.input :mediation_start, :class => "form-control", :width => "80" %>
            </div>
          </div>

          <strong>Resolution Type</strong><br>
          <select name="resolutiontype" id="resolutiontype"><option value=""></option>
            <option value="1">Resolved by Structure</option>
            <option value="2">Resolved by the community</option>
            <option value="3">Resolved with MLDL support</option>
            <option value="4">Other</option></select><br><br>
          <%#= f.collection_select(:resolutiontype_id, Resolutiontype.all, :id, :name, include_blank: true, html: {:id => rtype, :class => "form-control"}) %>

          <strong>Resolution Description</strong><br>
          Will save to Issue Record<br>

          <textarea name="resolution", id ="resolution" class="notefield" rows="4"></textarea><br>



        </div>

      </div>
      <div class="col-sm-12 actionbox">

        <div class="col-sm-3 radioin">
          <%= radio_button(:issueaction,  'actiontype', Actiontype::ONGOING, checked: true, id: "checkopen") %> Ongoing<br>

        </div>
        <div class="col-sm-9">

        </div>

      </div>

      <div class="col-sm-12 actionbox">



        <div class="col-sm-3 radioin">
          <%= radio_button(:issueaction,  'actiontype', Actiontype::ESCALATED, id: "checkrefer") %> Escalate Issue<br>

        </div>
        <div class="col-sm-9">
          <strong>Referral Note</strong><br>
          <textarea name="refernote", id ="refernote"  class="notefield" ></textarea><br>
        </div>


      </div>
      <div class="col-sm-12 actionbox">


        <div class="col-sm-3 radioin">
          <%= radio_button(:issueaction,  'actiontype', Actiontype::CANCELLED, id: "checkcancel") %> Cancel Issue<br>

        </div>
        <div class="col-sm-9">
          <strong>Cancellation Note</strong><br>
          <textarea name="cancelnote", id ="cancelnote"  class="notefield" ></textarea><br>
        </div>


      </div>


      <div class="col-sm-12 actionbox">


        <div class="col-sm-3 radioin">

        </div>
        <div class="col-sm-9">
          <strong>Mediation End Date</strong><br>
          <input type="text" name="mediate_end" id = "mediate_end" class="form-control" width="100">
        </div>


      </div>





      <div class="pull-left"><%= f.submit 'Record Mediation Result', :class => "btn btn-primary" %></div>


<% end %>


<script>
    $('#mediate_end').Zebra_DatePicker();
    $('#resolution_date').Zebra_DatePicker();

</script>


<script>

    $( "#mediationresult" ).validate({
        rules: {
            resolution: { required: "#checkresolve:checked" },
            resolution_date: { required: "#checkresolve:checked" },
            resolutiontype: { required: "#checkresolve:checked" },
            refernote: { required: "#checkrefer:checked" },
            mediate_end: { required: true },
            cancelnote: { required: "#checkcancel:checked" }

        }
    });
</script>

app/views/mediations/_mediations_admintable.html.erb
<table class="table">


  <thead>
  <tr>
    <th>Issue</th>
    <th>View</th>
    <th>Status</th>
    <th>Mediation start</th>
    <th>Mediation end</th>
    <th>Mediators</th>

    <th>Result</th>
    <th>Issue Resolution</th>
    <th>Mediation notes</th>

  </tr>
  </thead>

  <tbody>
  <% @mediations.each do |mediation| %>
      <% mymediators = Mediator.where(:mediation_id => mediation.id) %>
      <tr>
        <td><%= link_to mediation.issue.issuecode, mediation.issue %></td>
        <td><%= link_to 'View', mediation %></td>
        <td><%= mediation.status %></td>
        <td><%= mediation.mediate_start.strftime("%m/  %d/%Y") if mediation.mediate_start %></td>
        <td><%= mediation.mediate_end.strftime("%m/  %d/%Y") if mediation.mediate_end %></td>
        <td>

          <% mymediators.each do |med| %>
              <%= med.person.fullname %><br>
          <% end %>
        </td>

        <td><%= mediation.result_humanize %></td>
        <td><%= mediation.issue.resolution_date if mediation.issue.resolution_date %></td>
        <td><%= mediation.mediation_notes %></td>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/mediations/_mediations_table.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @tabhead %></h3>
  </div>
  <div class="panel-body">




    <table id="mediationstable" class="table table-striped table-hover">


  <thead>
  <tr>
    <th>Issue</th>
    <th>View</th>
    <th>Status</th>
    <th>Mediation start</th>
    <th>Mediation end</th>
    <th>Mediators</th>

    <th>Result</th>
    <th>Issue Resolution</th>
    <th>Mediation notes</th>

  </tr>
  </thead>

  <tbody>
  <% @mediations.each do |mediation| %>
      <% mymediators = Mediator.where(:mediation_id => mediation.id) %>
      <tr>
        <td><%= link_to mediation.issue.issuecode, mediation.issue %></td>
        <td><%= link_to 'View', mediation %></td>
        <td><%= mediation.status %></td>
        <td><%= mediation.mediate_start.strftime("%m/  %d/%Y") if mediation.mediate_start %></td>
        <td><%= mediation.mediate_end.strftime("%m/  %d/%Y") if mediation.mediate_end %></td>
        <td>

        <% mymediators.each do |med| %>
            <%= med.person.fullname %><br>
        <% end %>
        </td>

        <td><%= mediation.result_humanize %></td>
        <td><%= mediation.issue.resolution_date if mediation.issue.resolution_date %></td>
        <td><%= mediation.mediation_notes %></td>

      </tr>
  <% end %>
  </tbody>
</table>


  </div>
</div>





<script>
    $('#mediationstable').dataTable({
        'paging':   true,  // Table pagination
        'ordering': true,  // Column ordering
        'info':     true,  // Bottom left status text
// Text translation options
// Note the required keywords between underscores (e.g _MENU_)
        oLanguage: {
            sSearch:      'Search all columns:',
            sLengthMenu:  '_MENU_ records per page',
            info:         'Showing page _PAGE_ of _PAGES_',
            zeroRecords:  'Nothing found - sorry',
            infoEmpty:    'No records available',
            infoFiltered: '(filtered from _MAX_ total records)'
        }
    });

    $(document).ready(ready);
    $(document).on('page:load', ready);


</script>

app/views/mediations/edit.html.erb
<div class="container">

<h3>Editing Mediation</h3>

<%= render 'form' %>

<%= link_to 'Show', @mediation %> |
<%= link_to 'Back', mediations_path %>
</div>

app/views/mediations/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>


  <h2>Mediations List</h2>
  <div class="pull-right">
    <%= link_to 'New Mediation', new_mediation_path, :class => "btn btn-primary" %>
  </div>
  <%= render 'mediations_table' %>



</div>

app/views/mediations/new.html.erb
<div class="container">
  <h3>New Mediation</h3>
  <h4>Issue: <%= @issue.issuecode %> - <%= @issue.name %></h4>

<%= render 'form' %>

<%= link_to 'Back', mediations_path %>
</div>

app/views/mediations/show.html.erb
<style>

  .modal-mediationreport {
    width: 800px;
  }
  .modal-reopenmediation {
    width: 800px;
  }

</style>




<div class="container">



  <div class="row">
    <div class="col-md-12">

      <%= link_to 'Return to Mediations', mediations_path %><br>
      <%= link_to 'Back to Issue', @mediation.issue %><br>
      <span class="pageheader"><span style="color: #999">Mediation: </span><%= @mediation.mediationcode %></span>
      <!-- START row-->



    </div>

</div>




  <div class="row">

    <div class="col-sm-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">General</h3>
          <% if @canedit %>
              <% if @mediation.mediation_held != true %>
            <%= link_to 'Edit', edit_mediation_path(@mediation), :class => "btn btn-primary pull-right" %>
                  <% end %>
          <% end %>
        </div>

        <div class="panel-body">





          <p>
            <strong>Issue:</strong>
            <%= @mediation.issue.name %>
          </p>

          <p>
            <strong>Structure:</strong>
            <%= @mediation.issue.structure.name %>
          </p>
          <p>
            <strong>Mediation start:</strong>
            <%= @mediation.mediate_start.strftime("%m/  %d/%Y") if @mediation.mediate_start %>
          </p>

          <p>
            <strong>Mediation end:</strong>
            <%= @mediation.mediate_end.strftime("%m/  %d/%Y") if @mediation.mediate_end  %>
          </p>

          <p>
            <strong>Mediation notes:</strong>
            <%= @mediation.mediation_notes %>
          </p>


          <div class="form-group">
            <label class="col-sm-2">Documents</label>
            <div class="col-sm-10">
              <table class="table">

                <% @mediationdocs.each do |doc| %>
                    <tr>

                      <td>
                        <%= link_to doc.document_file_name , doc.document.url(:original, false) %>
                      </td>
                      <td>
                        <%= doc.document_updated_at %><br>
                      </td>
                      <td>
                        <% if @canedit %>
                            <%= link_to doc, method: :delete, data: { confirm: 'Are you sure you want to delete this document?' } do %><span class ="fa fa-minus-circle"></span><% end %>
                        <% end %>
                        </td>
                    </tr>

                <% end %>
              </table>
              <% if @canedit %>
                <%= simple_form_for @new_site_document do |form| %>
                    <%= form.hidden_field :documentable_id, :value => @mediation.id %>
                    <%= form.hidden_field :documentable_type, :value => 'mediation' %>
                    <%= form.input :document, as: :file, :label => false %>



                    <%= form.button :submit, :value => 'Upload Document', :class => "mb-sm btn btn-primary" %>
                <% end %>
              <% end %>

            </div>
          </div>


          <% if @canedit %>
                <div class="pull-right">
                  <%= link_to 'Delete', @mediation, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %>
                </div>
           <% end %>
        </div>

      </div>
      </div>
      <div class="col-sm-4">

      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Mediators</h3>

        </div>
        <div class="panel-body">

          <table class="table">
            <thead>
            <th>Name</th>
            <td>Title</td>
            <th>Email</th>
            <th>Organization/Title</th>
            <th></th>

            </thead>
            <tbody>
            <% @mediators.each do |p| %>
                <tr>
                  <td>  <%= link_to p.person.fullname, p.person %> </td>
                  <td><%= p.person.title %></td>
                  <td><%= p.person.email %></td>
                  <td><%= p.person.organization.name if p.person.organization_id %></td>

                  <td>
                    <% if current_user.mldlrole == 1 %>
                    <%= link_to deletemediator_path(:mediator_id => p.id),  data: { confirm: 'Are you sure you want to delete this Mediator?' } do %><em class="fa fa-minus-circle"></em><% end %>
                <% end %>
                  </td>
                        </tr>
            <% end %>
            </tbody>
          </table>


          <% if @canedit %>
            <hr>
            <small>Add Mediator</small><br>
            <%= render 'addmediator' %>
          <% end %>






        </div>

      </div>



    </div>
      <div class="col-sm-2">

    <div class="btn-group-vertical" role="group" aria-label="...">





      <% if @canedit %>


          <% if @mediation.mediation_held != true %>
              <%= link_to 'Mediation Result', '#mediation_result_modal', 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>

             
          <% else %>
              <%= link_to 'Reopen medation', '#trymodal', 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>
          <% end %>





          
          
       
      <% end %>
      <button class="btn btn-default">Print Mediation Report</button><br>




    </div>







  </div>

  </div>


  </div>


<div class="modal fade" id="trymodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-reopenmediation">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <small>Reopen MLDL Medation</small><br>
        <h4 class="modal-title" id="myModalLabel"><%= @mediation.mediationcode %></h4>
      </div>
      <div class="modal-body">
        <%= render 'reopenmediation', modal: true %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>


<div class="modal fade" id="mediation_result_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-mediationreport">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

        <h4 class="modal-title" id="myModalLabel">Report Mediation Result</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "mediationresults" %>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>