config/routes.rb
Rails.application.routes.draw do

  resources :infopopups
  resources :metrics
  resources :quarters
  resources :projects
  resources :agendas
  resources :userroles
  resources :actiontypes
  resources :mediators
  resources :mediations
  resources :participations
  resources :managers
  resources :assignments
  resources :roles

  #match 'users_admin/', to: 'users#create', via: :post, as: 'admin_create_user'

  #post 'admin_password_reset', to: 'users#password_reset', as: 'admin_password_reset'
  match '/users_password_reset', to: 'users#password_reset', via: :patch, as: 'admin_password_reset'

  resources :scopes
  resources :memberships
  resources :userroles
  resources :people
  resources :actiontypes
  resources :issueactions
  resources :actions
  resources :communities
  resources :appissues do
    collection { post :uploadcsv }
  end
  resources :structuretypes
  resources :statuses
  resources :categories
  resources :issues

  resources :organizations
  resources :meetings
  resources :counties
  resources :structures
  resources :districts



  #resources :searches

  resources :site_images
  resources :site_documents

  #devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_for :users
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  resources :posts
  resources  :people_structures
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  get 'resetpassword', :to => 'users#newpassword', as: 'resetpassword'
  get 'projectdashboard', :to => 'projects#dashboard', as: 'projectdashboard'
  get 'quarterlyreport', :to => 'projects#quarterlyreport', as: 'quarterlyreport'
  get 'structurereport', :to => 'projects#structurereport', as: 'structurereport'
  get 'projectlofa', :to => 'projects#lofa', as: 'projectlofa'
  get 'projectgrandgedeh', :to => 'projects#grandgedeh', as: 'projectgrandgedeh'
  get 'projectbong', :to => 'projects#bong', as: 'projectbong'
  get 'projectnimba', :to => 'projects#nimba', as: 'projectnimba'
  get 'managersmap', :to => 'structures#managersmap', as: 'managersmap'


  post 'addtoagenda', to: 'issuesactions#create_meetingagenda', as: 'addtoagenda'

  get 'resolution', to: 'issues#resolution', as: 'resolution'

  post 'addnote', to: 'issues#addnote', as: 'addnote'
  post 'addperson', to: 'structures#addperson', as: 'addperson'
  get 'adjustroles', to: 'users#adjustroles', as: 'adjustroles'
  get 'actionreport', to: 'visitors#actionreport', as: 'actionreport'
  get 'qtrreport', to: 'projects#qtrreport', as: 'qtrreport'
  get 'searchissues', to: 'issues#searchissues', as: 'searchissues'
  get 'issueresults', to: 'issues#searchresults', as: 'issueresults'
  get 'fixissue', to: 'appissues#fixissues', as: 'fixissues'

  get 'searchbyqtr', to: 'issues#searchbyqtr', as: 'searchbyqtr'
  get 'searchbyqtrresults', to: 'issues#searchbyqtrresults', as: 'searchbyqtrresults'
  get 'searchmeetings', to: 'meetings#searchmeetings', as: 'searchmeetings'
  
  get 'meetingresults', to: 'meetings#meetingresults', as: 'meetingresults'
  
  get 'monthlyreport', to: 'projects#monthlyreport', as: 'monthlyreport'
  get 'monthlyresults', to: 'projects#monthlyresults', as: 'monthlyresults'

  get 'qprreport', to: 'projects#qprreport', as: 'qprreport'
  get 'qprresults', to: 'projects#qprresults', as: 'qprresults'


  get 'countyadminreport', to: 'projects#countyadminreport', as: 'countyadminreport'
  get 'countyadminresults', to: 'projects#countyadminresults', as: 'countyadminresults'

  get 'newmldluser', to: 'users#newmldluser', as: 'newmldluser'
  post 'createuser', to: 'users#createuser', as: 'createuser'
  get 'deletemanager', to: 'structures#deletemanager', as: 'deletemanager'
  get 'deletemediator', to: 'mediations#deletemediator', as: 'deletemediator'
  get 'deletemembership', to: 'structures#deletemembership', as: 'deletemembership'
  get 'deleteparticipation', to: 'meetings#deleteparticipation', as: 'deleteparticipation'
  get 'deletedisputant', to: 'issues#deletedisputant', as: 'deletedisputant'
  get 'deletecommitteemember', to: 'issues#deletecommitteemember', as: 'deletecommitteemember'

  get 'meettemplate', to: 'meetings#blankmeeting', as: 'meettemplate'
  get 'othercategories', to: 'projects#othercategories', as: 'othercategories'
  get 'resultaudit', to: 'projects#resultaudit', as: 'resultaudit'
  post 'adddisputant', to: 'issues#adddisputant', as: 'adddisputant'
  post 'addcommitteemember', to: 'issues#addcommitteemember', as: 'addcommitteemember'
  post 'addparticipant', to: 'meetings#addparticipant', as: 'addparticipant'
  post 'addmediator', to: 'mediations#addmediator', as: 'addmediator'
  post 'addmemember', to: 'structures#addmembership', as: 'addmember'
  post 'addmanager', to: 'structures#addmanager', as: 'addmanager'
  get 'seedpeeps', to: 'people#seedpeeps', as: 'seedpeeps'
  get 'datacsv', to: 'issues#dumpfile', as: 'datacsv'
  get 'issuedump', to: 'issues#issuedump', as: 'issuedump'
  get 'structureissuedump', to: 'structures#structureissuedump', as: 'structureissuedump'

  get 'meetingcheck', to: 'meetings#meetingchecker', as: 'meetingcheck'
  get 'basicdata', to: 'projects#basicdatasetup', as: 'basicdata'
  get 'basictableoutput', to: 'projects#basictableoutput', as: 'basictableoutput'
  get 'downloadissues', to: 'issues#action_name', as: 'downloadissues'
  get 'seeder', to: 'issues#seeder', as: 'seeder'
  get 'clearsteve', to: 'projects#clearsteve', as: 'clearsteve'
  get '/tests2', :to => redirect('/tests2.html')
  root 'visitors#index'
  #get "counties/:county_id/districts", to: "application#districts", as: "districts", format: :json



end

app/models/structuretype.rb
class Structuretype < EnumerateIt::Base
  associate_values(
      cf:   [1, 'Community Forum'],
      dsc:  [2, 'District Council'],
      csc:  [3, 'County Council'],
      nsc:  [4, 'National Security Council']
  )
end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController

  before_action :set_structure, only: [:show, :edit, :update, :destroy]


  # GET /structures
  # GET /structures.json


def settime
  @project = Project.find(1)

  @yloop = [2013,2014,2015,2016,2017]
  @qloop = [1,4,7,10]

  @currentyear = Date.today.year
  @currentqtr = Date.today.beginning_of_quarter.month
  @currentbegin = Date.today.beginning_of_quarter
  @currentend = Date.today.end_of_quarter

  if params[:qtr].nil?
    @thisyear = @currentyear
    @thisqtr = @currentqtr


    #@thisyear = 2015
    #@thisqtr = 10
  else
    @thisyear = params[:year]
    @thisqtr = params[:qtr]
  end

  d0= @thisyear.to_s + '-' + @thisqtr.to_s + '-01 '
  @d2 = Time.parse(d0)


  if @thisqtr == 1
    @qtrname = @thisyear.to_s + '1st Qtr'
  elsif @thisqtr == 4
    @qtrname = @thisyear.to_s + '2nd Qtr'
  elsif @thisqtr == 7
    @qtrname =@thisyear.to_s + '3rd Qtr'
  elsif @thisqtr == 10
    @qtrname = @thisyear.to_s + '4th Qtr'
  else
    @qtrname = 'n/a'
  end


end





















  def index
    self.settime
    @nsc = Structure.find(1)
    @csc_structures = Structure.where('structuretype =?', Structuretype::CSC)
  end

  # GET /structures/1
  # GET /structures/1.json
  def show
    self.settime



    @summaryissues = @structure.project.cumulative_issues(0,@structure.id,0,0).count
    @summarymeetings = @structure.project.meetings(0,@structure.id,0,0).count
    @summarymediations = @structure.project.mediation_starts(0,@structure.id,0,0).count
    @summaryresolved = @structure.project.total_resolved(@structure.id,0,0).count
    @summaryopenissues =  @structure.project.currentopen(0,@structure.id,0,0).count
    @summaryopenmediations = @structure.project.openmediations(0,@structure.id).count


    if @structure.ismanager(current_user.id) or current_user.mldlrole == 1 or @structure.iscscmanager(current_user)

         @canedit = true
    else
         @canedit = false
    end



    @issues= Issue.where('structure_id = ?', @structure.id).order('created_at DESC')
    myissueids=@issues.pluck(:id)

    @allcats = Category.all
    @alldistricts = District.all
    @myactions = Issueaction.where(structure_id: @structure.id).order('created_at DESC').limit(20)
    @mediations = Mediation.where(issue_id: myissueids)
    @mypeople= Membership.where('structure_id = ?', @structure.id)
    @mymanagers = Manager.where('structure_id = ?', @structure.id)
    @structuredocs = SiteDocument.where('documentable_type = ? and documentable_id = ?', 'structure', @structure.id)
    @new_site_document = SiteDocument.new
    @meetings = Meeting.where(structure_id: @structure.id)
    @openmeetings = @meetings.where(meeting_held: true)

    @parent = Structure.find(@structure.parent_id) if @structure.parent_id
    #@availablemanagers = Userrole.where('role_id = ?', 2)
    @availablemanagers = User.where('mldlrole =? ', 2)
    #@availablemanagers = []
    #users=Userrole.where('role_id = ?', 2)
    #users.each do |u|
    #  @availablemanagers.append(User.find(u.user_id))
    #end
    @issue = Issue.new
    @meeting = Meeting.new
    @available_people = Person.all
    @person = Person.new
    @membership = Membership.new
    @manager = Manager.new






    catsids = CategoriesStructure.where('category_id > 0 and structure_id = ?', @structure.id).order('vcount desc')
    catcolor = 1
    cattotals = ''
    catsids.each do |c|

      slice = CategoryColor.find(catcolor)
      c1 = '{ "label": "' + c.category.name + '", "value": ' + c.vcount.to_s + ', "color": "' + slice.name  + '"}'
      if c != catsids.last
        c1 = c1 + ','
      end

      catcolor = catcolor + 1


      cattotals = cattotals + c1

    end
    @catdata =   cattotals



    distids = DistrictsStructure.where('district_id > 0 and structure_id = ?', @structure.id).order('vcount desc')
    distcolor = 1
    disttotals = ''
    distids.each do |d|
      slice = CategoryColor.find(distcolor)
      d1 = '{ "label": "' + d.district.name + '", "value": ' + d.vcount.to_s + ', "color": "' + slice.name  + '"}'
      if d != distids.last
        d1 = d1 + ','
      end
      if distcolor == 10
        distcolor = 2
      else
        distcolor = distcolor + 1
      end




      disttotals = disttotals + d1

    end
    @distdata =   disttotals











  end

  # GET /structures/new
  def new

    @structure = Structure.new

  end

  # GET /structures/1/edit
  def edit

  end




  # POST /structures
  # POST /structures.json
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        Userlog.create(user_id: current_user.id, loggable_type: 'Structure', loggable_id: @structure.id, action: 'Create')
        format.html { redirect_to @structure, notice: 'Structure was successfully created.' }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1
  # PATCH/PUT /structures/1.json
  def update

    respond_to do |format|
      if @structure.update(structure_params)
        Userlog.create(user_id: current_user.id, loggable_type: 'Structure', loggable_id: @structure.id, action: 'Update')
        format.html { redirect_to @structure, notice: 'Structure was successfully updated.' }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1
  # DELETE /structures/1.json
  def destroy
    @structure.destroy
    respond_to do |format|
      format.html { redirect_to structures_url, notice: 'Structure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def deletemanager

    m=Manager.find(params[:manager_id]).destroy
    s = Structure.find(m.structure_id)

    #thismanager=Manager.find(params[:manager_id])
    #delmanager= thismanager.destroy
    #s=Structure.find(thismanager.structure_id)
    respond_to do |format|
      format.html { redirect_to s, notice: 'Manager has been removed.' }
      format.json { head :no_content }
    end


  end


  def structureissuedump
    structure=Structure.find(params[:structure_id])
    @sheetname = "MLDL Issues - " + structure.name
    @issues = Issue.where(structure_id: params[:structure_id])
    render xlsx:'issues', template: 'issues/issuedump.xlsx.axlsx', filename: 'mldlissues.xlsx'
  end



  def deletemembership

    m=Membership.find(params[:membership_id])

    s = Structure.find(m.structure_id)
    m.destroy!

    respond_to do |format|
      format.html { redirect_to s, notice: 'Manager has been removed.' }
      format.json { head :no_content }
    end


  end



  def addmembership

    @membership = Membership.new
    structure=Structure.find(params[:structure_id])
    @membership.structure_id = structure.id
    if params[:addpeep]
      peep=Person.create(name_first: params[:fname], name_last: params[:lname], email: params[:email], title: params[:title], organization_id: params[:organization_id])
      @membership.person_id = peep.id
    else
      @membership.person_id = params[:person_id]
    end

    respond_to do |format|
      if @membership.save
        format.html { redirect_to structure, notice: 'Membership was successfully added to Structure.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end

  end


  def addmanager

    @manager = Manager.new
    structure=Structure.find(params[:structure_id])
    @manager.structure_id = structure.id
    @manager.user_id = params[:user_id]

    respond_to do |format|
      if @manager.save
        format.html { redirect_to structure, notice: 'Manager was successfully added.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end

  end


  def managersmap
@csc_structures = Structure.where(structuretype: 3)
render 'managersmap'

  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def structure_params
      params.require(:structure).permit(:name, :structuretype, :district_id, :county_id, :parent_id, :default_location, memberships:[:person_id, :structure_id])
    end
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/views/structures/_addmember.html.erb
<%= form_tag addmember_path do %>
    <%= render 'people/addpeopletoobject' %>
    <%= hidden_field_tag(:structure_id, @structure.id) %>
    <div class="actions">
      <%= submit_tag 'Submit', :class => "btn btn-small btn-primary" %>
    </div>


<% end %>

app/views/structures/_general.html.erb
<div class="row">
  <div class="col-sm-5">



    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">General Information</h3>
        <% if @canedit %>
        <%= link_to 'Edit', edit_structure_path(@structure), :class => "btn btn-small btn-primary pull-right"   %>
        <% end %>
            </div>
      <div class="panel-body">
        <div class="form-horizontal">


          <div class="form-group">
            <label class="col-sm-3">Type (Level)</label>
            <div class="col-sm-9">
              <strong> <%= @structure.structuretype_humanize if @structure.structuretype %></strong>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3">County</label>
            <div class="col-sm-9">
              <strong> <%= @structure.district.county.name if @structure.district_id %></strong>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3">District</label>
            <div class="col-sm-9">
              <strong> <%= @structure.district.name if @structure.district_id %></strong>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3">Parent Structure</label>
            <div class="col-sm-9">
              <strong> <%= link_to @parent.name, @parent if @structure.parent_id %></strong>
            </div>
          </div>

          <div class="form-group">

            <label class="col-sm-2">Default Meeting Location</label>
            <div class="col-sm-9">
              <strong> <%= @structure.default_location  %></strong>
            </div>
          </div>

        </div>
      </div>
    </div>
</div>
  <div class="col-sm-5">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Management (Users)</h3>
        <%#= link_to 'Add Manager', '#new_mgmt_modal', 'data-toggle' => 'modal', :class => "btn btn-success pull-right" %>
      </div>
      <div class="panel-body">
<table class="table">
        <% @mymanagers.each do |a| %>
      <tr>
        <td>
          <%= a.user.name %>
        </td>
        <td>
          <% if @canedit %>
          <%= link_to deletemanager_path(:manager_id => a.id),  data: { confirm: 'Are you sure?' } do %><em class="fa fa-minus-circle"></em><% end %>
            <% end %>
        </td>

      </tr>

        <% end %>
</table>
        <hr><br><br>
        <small>Add Manager</small><br>


        <script type="text/javascript">
          $(document).ready(function() {
            $(".selectmanager").select2();
          });
        </script>
        <% if @canedit %>
            <%= form_tag addmanager_path do |f| %>

                Add Current System Managers to this Stucture
                <div class="field">
                  <%#= debug @availablemanagers  %><br>
                  <%= select_tag 'user_id', options_from_collection_for_select(@availablemanagers, :id, :name), include_blank: true, :class => "selectmanager" %>


                </div>



                <%= hidden_field_tag(:structure_id, @structure.id) %>
                <div class="actions">
                  <%= submit_tag 'Submit', :class => "btn btn-small btn-primary" %>
                </div>
            <% end %>
        <% end %>

      </div>
    </div>




  </div>






</div>
<% if @structure.ismanager(current_user.id) %>

  <%= link_to 'Delete', @structure, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %>
<% end %>

app/views/structures/edit.html.erb
<div class="container">
<h3>Editing Structure</h3>

<%= render 'form' %>

<%= link_to 'Show', @structure %> |
<%= link_to 'Back', structures_path %>
</div>

app/views/structures/new.html.erb
<div class="container">
<h1>New Structure</h1>

<%= render 'form' %>

<%= link_to 'Back', structures_path %>
</div>

app/views/structures/show.html.erb
<style>

.modal-addmeeting {
width: 800px;
}
.modal-addissue {
width: 800px;
}

 .panel-info > .panel-heading {
   background-color: <%= @structure.structurecolorcode(@structure.structuretype) %> ;
 }



</style>






<script type="text/javascript">
  $(document).ready(function() {
    $(".chosen-select").select2();
  });

</script>


<div class="row">
  <div class="col-md-6">

    <%= link_to 'Return to Structures', structures_path %><br>
    <span class="pageheader"><span style="color: #999">Structure: </span><%= @structure.name %></span>
    <!-- START row-->

  </div>
  <div class="col-md-6">

    <div class="pull-right">
      <% if @canedit %>
          <div class="pull-right"><br>
            <%= link_to 'New Issue', new_issue_path(:structure_id => @structure.id), 'data-no-turbolink' => true, :class => "btn btn-success"  %>
            <%#= link_to 'New Issue', '#new_issue_modal', 'data-toggle' => 'modal', :class => "btn btn-success" %>
            <%= link_to "New Meeting", new_meeting_path(:structure_id => @structure.id), :class => "btn btn-success" %>

            <%= form_tag(issuedump_path, method: :get) do %>
                  <% hidden_field_tag(:structure_id => @structure.id) %>
                  <%= submit_tag 'Download data', class: 'btn btn-sm btn-primary' %>
              <% end %>





            <%#= link_to "Issue Dump XLS", structureissuedump_path(:structure_id => @structure.id), :class => "btn btn-default" %>
          </div>
      <% end %>

    </div>

  </div>
</div>


<!-- Page content-->












  <div class="row">


        <div class="col-sm-12">




          <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#viewdash">Dashboard</a></li>
            <li><a data-toggle="tab" href="#viewissues">Issues</a></li>
            <li><a data-toggle="tab" href="#viewgeneral">General</a></li>
            <li><a data-toggle="tab" href="#viewmeetings">Meetings</a></li>
            <li><a data-toggle="tab" href="#viewmediations">Mediations</a></li>
            <li><a data-toggle="tab" href="#viewmembers">Members</a></li>
            <li><a data-toggle="tab" href="#viewdocs">Documents</a></li>
          </ul>

          <div class="tab-content">
            <div id="viewdash" class="tab-pane fade in active">

              <%= render partial: 'structure_dashboard' %>
            </div>

            <div id="viewgeneral" class="tab-pane fade">

              <%= render partial: 'structures/general' %>
            </div>

            <div id="viewissues" class="tab-pane">
              <% @tabhead = @structure.name + ' Issues' %>
              <%= render partial: 'issues/issues_table' %>
            </div>
            <div id="viewmeetings" class="tab-pane fade">
              <% @tabhead = @structure.name + ' Meetings' %>
              <%= render partial: 'meetings/meetings_table' %>
            </div>
            <div id="viewmediations" class="tab-pane fade">
              <% @tabhead = @structure.name + ' Mediations' %>
              <%= render partial: 'mediations/mediations_table' %>
            </div>
            <div id="viewmembers" class="tab-pane fade">

              <div class="panel panel-info">
                <div class="panel-heading">
                  <h3 class="panel-title">People (non Users linked to Structure)</h3>
                  <%#= link_to 'Add Person', '#new_person_modal', 'data-toggle' => 'modal', :class => "btn btn-success pull-right" %>
                </div>
                <div class="panel-body">

                  <table class="table">
                    <thead>
                    <th>Name</th>
                    <td>Title</td>
                    <th>Email</th>
                    <th>Organization/Title</th>
                    <th></th>

                    </thead>
                    <tbody>
                    <% @mypeople.each do |p| %>
                        <tr>
                          <td>  <%= link_to p.person.fullname, p.person %> </td>

                          <td><%= p.person.title %></td>
                          <td><%= p.person.email %></td>
                          <td><%= p.person.organization.name if p.person.organization_id %></td>
                          <td>
                            <% if @canedit %>
                            <%= link_to deletemembership_path(:membership_id => p.id),  data: { confirm: 'Are you sure?' } do %><em class="fa fa-minus-circle"></em><% end %>
                            <% end %>
                          </td>

                        </tr>
                    <% end %>
                    </tbody>
                  </table>

                  <hr>
                  <% if @canedit %>
                    <small>Link Person to Structure</small><br>
                    <%= render 'addmember' %>


                  <% end %>

                  <script type="text/javascript">
                    $(document).ready(function() {
                      $(".js-example-basic-single").select2();
                    });

                  </script>

                </div>

              </div>
            </div>





            <div id="viewdocs" class="tab-pane fade">






              <div class="panel panel-info">
                <div class="panel-heading">
                  Documents

                </div>
                <div class="panel-body">



                  <table class="table">

                    <% @structuredocs.each do |doc| %>
                        <tr>

                          <td>
                            <%= link_to doc.document_file_name , doc.document.url(:original, false) %>
                          </td>
                          <td>
                            <%= doc.document_updated_at %><br>
                          </td>
                          <td>
                            <% if @canedit %>
                                <%= link_to doc, method: :delete, data: { confirm: 'Are you sure you want to delete this document?' } do %><span class ="fa fa-minus-circle"></span><% end %>
                            <% end %>
                          </td>
                        </tr>

                    <% end %>
                  </table>


                  <br><BR>

                  <% if @canedit %>
                      <%= simple_form_for @new_site_document do |form| %>
                          <%= form.hidden_field :documentable_id, :value => @structure.id %>
                          <%= form.hidden_field :documentable_type, :value => 'structure' %>
                          <%= form.input :document, as: :file, :label => false %>
                          <%= form.button :submit, :value => 'Upload Document', :class => "mb-sm btn btn-primary" %>
                      <% end %>
                  <% end %>




                </div>
              </div>





            </div>









          </div>










        </div>
  </div>









      </div>






<div class="modal fade" id="new_mgmt_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-addmgmt">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <small>Add Management to Structure</small><br>
        <h4 class="modal-title" id="myModalLabel"><%= @structure.name %></h4>
      </div>
      <div class="modal-body">
        <%= render 'addmanager', modal: true %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

<div class="modal fade" id="new_issue_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-addmeeting">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <small>Add New Issue to Structure</small><br>
        <h4 class="modal-title" id="myModalLabel"><%= @structure.name %></h4>

        <div id="error_explanation" style="display:none;">
      </div>
      <div class="modal-body">
        <%= render 'addstructureissue', modal: true %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

<div class="modal fade" id="new_meeting_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-addmeeting">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <small>Add New Structure Meeting</small><br>
        <h4 class="modal-title" id="myModalLabel"><%= @structure.name %></h4>
      </div>
      <div class="modal-body">
        <%= render 'addstructuremeeting', modal: true %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>











<script>
  $(function(){

  var options = {
    series: {
      pie: {
        show: true,
        innerRadius: 0,
        label: {
          show: true,
          radius: 0.8,
          formatter: function (label, series) {
            return '<div class="flot-pie-label">' +
                      //label + ' : ' +
                    Math.round(series.percent) +
                    '%</div>';
          },
          background: {
            opacity: 0.8,
            color: '#222'
          }
        }
      }
    }
  };

  var chart = $('.chart-pie');
  if(chart.length)
    $.plot("#placeholder", <%= @piestatic %>, options);
  });




    $('#new_mgmt_modal').on('submit', function() {
      $('#new_mgmt_modal').modal('hide');
    })


    $('#new_issue_modal').on('submit', function() {
      $('#new_issue_modal').modal('hide');
    })

    $('#new_meeting_modal').on('submit', function() {
      $('#new_meeting_modal').modal('hide');
    })


  </script>