config/routes.rb
Rails.application.routes.draw do

  resources :infopopups
  resources :metrics
  resources :quarters
  resources :projects
  resources :agendas
  resources :userroles
  resources :actiontypes
  resources :mediators
  resources :mediations
  resources :participations
  resources :managers
  resources :assignments
  resources :roles

  #match 'users_admin/', to: 'users#create', via: :post, as: 'admin_create_user'

  #post 'admin_password_reset', to: 'users#password_reset', as: 'admin_password_reset'
  match '/users_password_reset', to: 'users#password_reset', via: :patch, as: 'admin_password_reset'

  resources :scopes
  resources :memberships
  resources :userroles
  resources :people
  resources :actiontypes
  resources :issueactions
  resources :actions
  resources :communities
  resources :appissues do
    collection { post :uploadcsv }
  end
  resources :structuretypes
  resources :statuses
  resources :categories
  resources :issues

  resources :organizations
  resources :meetings
  resources :counties
  resources :structures
  resources :districts



  #resources :searches

  resources :site_images
  resources :site_documents

  #devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_for :users
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  resources :posts
  resources  :people_structures
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  get 'resetpassword', :to => 'users#newpassword', as: 'resetpassword'
  get 'projectdashboard', :to => 'projects#dashboard', as: 'projectdashboard'
  get 'quarterlyreport', :to => 'projects#quarterlyreport', as: 'quarterlyreport'
  get 'structurereport', :to => 'projects#structurereport', as: 'structurereport'
  get 'projectlofa', :to => 'projects#lofa', as: 'projectlofa'
  get 'projectgrandgedeh', :to => 'projects#grandgedeh', as: 'projectgrandgedeh'
  get 'projectbong', :to => 'projects#bong', as: 'projectbong'
  get 'projectnimba', :to => 'projects#nimba', as: 'projectnimba'
  get 'managersmap', :to => 'structures#managersmap', as: 'managersmap'


  post 'addtoagenda', to: 'issuesactions#create_meetingagenda', as: 'addtoagenda'

  get 'resolution', to: 'issues#resolution', as: 'resolution'

  post 'addnote', to: 'issues#addnote', as: 'addnote'
  post 'addperson', to: 'structures#addperson', as: 'addperson'
  get 'adjustroles', to: 'users#adjustroles', as: 'adjustroles'
  get 'actionreport', to: 'visitors#actionreport', as: 'actionreport'
  get 'qtrreport', to: 'projects#qtrreport', as: 'qtrreport'
  get 'searchissues', to: 'issues#searchissues', as: 'searchissues'
  get 'issueresults', to: 'issues#searchresults', as: 'issueresults'
  get 'fixissue', to: 'appissues#fixissues', as: 'fixissues'

  get 'searchbyqtr', to: 'issues#searchbyqtr', as: 'searchbyqtr'
  get 'searchbyqtrresults', to: 'issues#searchbyqtrresults', as: 'searchbyqtrresults'
  get 'searchmeetings', to: 'meetings#searchmeetings', as: 'searchmeetings'
  
  get 'meetingresults', to: 'meetings#meetingresults', as: 'meetingresults'
  
  get 'monthlyreport', to: 'projects#monthlyreport', as: 'monthlyreport'
  get 'monthlyresults', to: 'projects#monthlyresults', as: 'monthlyresults'

  get 'qprreport', to: 'projects#qprreport', as: 'qprreport'
  get 'qprresults', to: 'projects#qprresults', as: 'qprresults'


  get 'countyadminreport', to: 'projects#countyadminreport', as: 'countyadminreport'
  get 'countyadminresults', to: 'projects#countyadminresults', as: 'countyadminresults'

  get 'newmldluser', to: 'users#newmldluser', as: 'newmldluser'
  post 'createuser', to: 'users#createuser', as: 'createuser'
  get 'deletemanager', to: 'structures#deletemanager', as: 'deletemanager'
  get 'deletemediator', to: 'mediations#deletemediator', as: 'deletemediator'
  get 'deletemembership', to: 'structures#deletemembership', as: 'deletemembership'
  get 'deleteparticipation', to: 'meetings#deleteparticipation', as: 'deleteparticipation'
  get 'deletedisputant', to: 'issues#deletedisputant', as: 'deletedisputant'
  get 'deletecommitteemember', to: 'issues#deletecommitteemember', as: 'deletecommitteemember'

  get 'meettemplate', to: 'meetings#blankmeeting', as: 'meettemplate'
  get 'othercategories', to: 'projects#othercategories', as: 'othercategories'
  get 'resultaudit', to: 'projects#resultaudit', as: 'resultaudit'
  post 'adddisputant', to: 'issues#adddisputant', as: 'adddisputant'
  post 'addcommitteemember', to: 'issues#addcommitteemember', as: 'addcommitteemember'
  post 'addparticipant', to: 'meetings#addparticipant', as: 'addparticipant'
  post 'addmediator', to: 'mediations#addmediator', as: 'addmediator'
  post 'addmemember', to: 'structures#addmembership', as: 'addmember'
  post 'addmanager', to: 'structures#addmanager', as: 'addmanager'
  get 'seedpeeps', to: 'people#seedpeeps', as: 'seedpeeps'
  get 'datacsv', to: 'issues#dumpfile', as: 'datacsv'
  get 'issuedump', to: 'issues#issuedump', as: 'issuedump'
  get 'structureissuedump', to: 'structures#structureissuedump', as: 'structureissuedump'

  get 'meetingcheck', to: 'meetings#meetingchecker', as: 'meetingcheck'
  get 'basicdata', to: 'projects#basicdatasetup', as: 'basicdata'
  get 'basictableoutput', to: 'projects#basictableoutput', as: 'basictableoutput'
  get 'downloadissues', to: 'issues#action_name', as: 'downloadissues'
  get 'seeder', to: 'issues#seeder', as: 'seeder'
  get 'clearsteve', to: 'projects#clearsteve', as: 'clearsteve'
  get '/tests2', :to => redirect('/tests2.html')
  root 'visitors#index'
  #get "counties/:county_id/districts", to: "application#districts", as: "districts", format: :json



end

app/models/meeting.rb
class Meeting < ActiveRecord::Base

  belongs_to :structure
  #has_many :issueactions, :dependent => :destroy

  has_many :agendas, :dependent => :destroy
  has_many :issues, :through => :agendas

  has_many :participations, :dependent => :destroy
  has_many :people, :through => :participations

  has_many :issueactions, :dependent => :destroy

  has_many :site_documents


  def meetingid

    mdate = self.meeting_on.strftime("%Y-%m").to_s
    structure = self.structure.short
    structurename = self.structure.name

    meetingid = ('MTG ' + mdate + '-' + structure + '-'  + self.id.to_s)
    return meetingid
  end



  def status
    if self.meeting_held
      sname = 'Closed (Held)'
    else
      sname = 'Scheduled'
    end
  end

  def addressedagendas
    addressed = Agenda.where(meeting_id: self.id, addressed: :true)
    return addressed.count
  end

  def unaddressedagendas
    addressed = Agenda.where(meeting_id: self.id, addressed: nil)
    return addressed.count
  end



end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show

    if @meeting.structure.ismanager(current_user.id) or current_user.mldlrole == 1
      @canedit = true
    end
    @myagendas = Agenda.where(meeting_id: @meeting.id)
    @unheardagendas = Agenda.where('meeting_id =? and (addressed is null or addressed = ?)', @meeting.id, :false).count
    @participants = Participation.where('meeting_id = ?', @meeting.id)
    @myparent = Structure.find(@meeting.structure.parent_id)
    @participation = Participation.new
    @available_people = Person.all
    @issue = Issue.new
    @issueaction = Issueaction.new
    @meetingdocs = SiteDocument.where('documentable_type = ? and documentable_id = ?', 'meeting', @meeting.id)
    @new_site_document = SiteDocument.new


    @pdfname = 'mldl_meeting_' + @meeting.id.to_s

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: @pdfname
        # pdf = IssuePdf.new(@issue)
        #send_data pdf.render, filename: "order_#{@issue.issuecode}.pdf",
        #         type: "application/pdf",
        #        disposition: "inline"
      end
    end








  end



  def searchmeetings

    @allstructures = Structure.order(:id)
    @allpersons = Person.all


  end

  def meetingresults

    searchterm = params[:search_term]
    searchresults = Meeting.all

    searchresults = Meeting.where('structure_id in (?)', params[:structure_ids]) if !params[:structure_ids].blank?

    #searchresults = Meeting.where('name like ? or description like ? or community like  ? ', "%#{searchterm}%", "%#{searchterm}%", "%#{searchterm}%") if !params[:search_term].blank?

    @Meetings = searchresults
    render 'index'
  end



  def meetingchecker

    getmeetingids = Meeting.pluck(:id)

    badids = Issueaction.where(actiontype: 2).where.not(meeting_id: getmeetingids).destroy_all
    puts
    puts badids

    num=Issueaction.where(actiontype: 2).where(meeting_id: nil).destroy_all

    @cleanedout = num
     render 'index'
  end












  # GET /meetings/new
  def new
    @meeting = Meeting.new
    @meeting.structure_id = params[:structure_id] if params[:structure_id]
    @openissues = Issue.where(structure_id: @meeting.structure_id, status: Status::ONGOING)
  end

  # GET /meetings/1/edit
  def edit

    agendaissueids = Agenda.where(meeting_id: @meeting.id).pluck(:issue_id)

    @openissues = Issue.where('(structure_id = ? and (status = ? or status = ?)) or id in (?)',  @meeting.structure_id, Status::NEW, Status::ONGOING, agendaissueids )
  end

  # POST /meetings
  # POST /meetings.json
  def create

    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        Userlog.create(user_id: current_user.id, loggable_type: 'Meeting', loggable_id: @meeting.id, action: 'Create')
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update

 puts params[:meeting][:issue_ids]


 if params[:meeting][:issue_ids]

   issuesadded =params[:meeting][:issue_ids].reject { |e| e.to_s.empty? }
   Issueaction.where('actiontype = ? and meeting_id = ? and issue_id in (?)', Actiontype::AGENDA, params[:id], issuesadded).destroy_all


   issuesadded.each do |i|

      Issueaction.create(meeting_id: @meeting.id, structure_id: @meeting.structure_id, issue_id: i, actiontype: Actiontype::AGENDA)
    end
  end

    respond_to do |format|
      if @meeting.update(meeting_params)
        Userlog.create(user_id: current_user.id, loggable_type: 'Meeting', loggable_id: @meeting.id, action: 'Update')
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def addparticipant



    @participant = Participation.new
    meeting=Meeting.find(params[:meeting_id])
    @participant.meeting_id = meeting.id
    if params[:addpeep]
      peep=Person.create(name_first: params[:fname], name_last: params[:lname], email: params[:email], title: params[:title], organization_id: params[:organization_id])
      @participant.person_id = peep.id
    else
      @participant.person_id = params[:person_id]
    end

    respond_to do |format|
      if @participant.save
        format.html { redirect_to meeting, notice: 'Participation was successfully created.' }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end




  end

  def blankmeeting
    @structure= Structure.find(params[:structure_id])

  @pdfname = 'mldl_meeting_template'

  respond_to do |format|
    format.html
    format.pdf do
      render pdf: @pdfname
      # pdf = IssuePdf.new(@issue)
      #send_data pdf.render, filename: "order_#{@issue.issuecode}.pdf",
      #         type: "application/pdf",
      #        disposition: "inline"
    end
  end






end







  def deleteparticipation
    p=Participation.find(params[:participation_id]).destroy
    m = Meeting.find(p.meeting_id)
    respond_to do |format|
      format.html { redirect_to m, notice: 'Meeting Participant has been removed.' }
      format.json { head :no_content }
    end
  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:meeting_on, :structure_id, :location, :duration, :starts_at, :attendees_male, :attendees_females, :meeting_held, :closenote, :reopennote, issue_ids: [])
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_addmeetingissues.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for (@issue), :data => {:parsley_validate => "", :novalidate => ""}  do |f| %>

    <div class="form-horizontal">
      <% if @issue.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

            <ul>
              <% @issue.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>



      <div class="form-group">
        <%= f.label :name, :class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :name, :size => 100, :class => "form-control", :required => 'required' %>

        </div>
      </div>




      <div class="form-group">
        <%= f.label 'District', :class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.collection_select(:district_id, District.all, :id, :name, {}, {required: true, include_blank: true } ) %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label 'Community of Origin', :class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :community, :size => 100, :class => "form-control", :required => 'required' %>

        </div>
      </div>



      <div class="form-group">
        <%= f.label 'Disputants', :class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :disputant, :size => 100, :class => "form-control" %>

        </div>
      </div>



      <div class="form-group">
        <%= f.label :description, :class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_area :description, :id => "descedit", :cols => "100", :rows => "8" %>

        </div>
      </div>





      <div class="form-group">
        <%= f.label 'Issue Origin', :class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%#= f.select :category_id, Category.all, {}, {class: 'form-control', required: true } %>
          <%= f.collection_select(:scope_id, Scope.all, :id, :name, {}, {include_blank: true } ) %>

        </div>
      </div>



      <div class="form-group">
        <%= f.label :category_id, :class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%#= f.select :category_id, Category.all, {}, {class: 'form-control', required: true } %>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {include_blank: true } ) %>

        </div>
      </div>


      <%= hidden_field_tag(:meeting_id, @meeting.id) %>
      <%= hidden_field(:issue, :structure_id, :value => @meeting.structure_id) %>
      <%= hidden_field_tag(:frommeeting, 1) %>
      <div class="form-group">
        <div class = "col-sm-2 control-label"></div>
        <div class="col-sm-10">
          <%= f.submit :class => "btn btn-primary" %>

        </div>
      </div>

    </div>
<% end %>

<

app/views/meetings/_addparticipant.html.erb
<%= form_tag addparticipant_path do %>

    <%= render 'people/addpeopletoobject' %>
    <%= hidden_field_tag(:meeting_id, @meeting.id) %>
    <div class="actions">
      <%= submit_tag 'Submit', :class => "btn btn-small btn-primary" %>
    </div>
<% end %>

app/views/meetings/_closemeeting.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@meeting, multipart: true, remote: false, html: {role: :form, 'data-model' => 'meeting', id: 'close_meeting_form'}) do |f| %>

    <%= hidden_field(:meeting, :meeting_held, :value => true) %>
    <div class="field">
      <%= f.label 'Close Out Note:' %><br>
      This Note will be saved to the Meeting record.<br>
      <%= f.text_area :closenote,  cols: "120", rows: "12" %>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', :class => "btn-small btn-primary" %>
    </div>
<% end %>

app/views/meetings/_form.html.erb
  <% if @meeting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

        <ul>
          <% @meeting.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

    <%= simple_form_for @meeting do |f| %>

        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">




                  <div class="form-group">
                    <%= f.label :structure_id, :class => "col-sm-3 control-label" %>
                    <div class="col-sm-9">
                      <% if params[:structure_id] %>
                          <%= f.hidden_field :structure_id, :value => params[:structure_id] %>

                          <%= @meeting.structure.name %><br><br>
                      <% else %>

                          <%= f.collection_select(:structure_id, Structure.all, :id, :name, include_blank: true, :class => "form-control") %><br><br>
                      <% end %>


                    </div>
                  </div>


                  <div class="form-group">
                    <%= f.label 'Meeting On', :class => "col-sm-3 control-label" %>
                    <div class="col-sm-9">
                      <% if @meeting.meeting_on.nil? %>
                      <%= f.text_field :meeting_on, :id => "datepicker-meeton", value: Date.today.to_s(:db) %>
                      <% else %>
                          <%= f.text_field :meeting_on, :id => "datepicker-meeton" %>
                    <% end %>


                        <%#= f.date_select :meeting_on, :default => Time.now.to_date %><br><br>

                    </div>
                  </div>

                  <div class="form-group">
                    <%= f.label 'Time Start', :class => "col-sm-3 control-label" %>
                    <div class="col-sm-9">

                        <%= f.time_select :starts_at, :ignore_date => true, :default => {:hour => '07', :minute => '00'} %><br><br>
                   </div>
                  </div>



                    <div class="form-group">
                        <%= f.label 'Location (with default)', :class => "col-sm-3 control-label" %>
                        <div class="col-sm-9">
                             <%= f.text_field :location, :size => 40, :value => @meeting.structure.default_location, :class => "form-control" %><br><br>
                        </div>
                    </div>


                  <div class="form-group">
                    <%= f.label 'Duration', :class => "col-sm-3 control-label" %>
                    <div class='col-sm-9'>
                      <%=f.select :duration, (0..8).step(0.25).map{|x| ["#{ x }", x.to_f]}, {}, include_blank: true %> (hours)<br><br>

                    </div>


                    <div class="form-group">
                      <%= f.label 'Attendees Male', :class => "col-sm-3 control-label" %>
                      <div class="col-sm-9">
                        <%= f.text_field :attendees_male %><br><br>
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.label 'Attendees Female', :class => "col-sm-3 control-label" %>
                      <div class="col-sm-9">
                        <%= f.text_field :attendees_females %><br><br>
                      </div>
                    </div>





                    <div class="form-group">
                      <div class='col-sm-3'>

                        </div>
                      <div class='col-sm-9'>

                        <%= f.check_box :meeting_held %>
                     <%= f.label ' Has the Meeting been held?' %>
                    </div>
                  </div>




                    <div class="form-group">
                      <div class = "col-sm-2 control-label"></div>
                      <div class="col-sm-10">
                        <%= f.submit :class => "btn btn-primary" %>

                      </div>
                    </div>











            </div>



        </div>

</div>
          </div>

  <div class="col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">


                        <%= hidden_field_tag "meeting[issue_ids][]", nil %>
                        <h3><%= @meeting.structure.name %> Open Issues</h3>
                        <small>Does not include Resolved Issues or Issues in Mediation</small>
                        <table class="table table-striped">
                        <thead>

                        <th>Add to Agenda</th>

                        <th width="110">ID</th>
                        <th>Name</th>
                        <th>Status</th>

                        <th>Disputants</th>
                        <th>Community</th>

                        </thead>
                        <tbody>


                        <% @openissues.all.each do |issue| %>

                            <% statusbox1 = 'btn btn-'+ issue.issuestatus(issue.status) %>

                             <tr><td>  <%= check_box_tag "meeting[issue_ids][]", issue.id, @meeting.issue_ids.include?(issue.id), id: dom_id(issue) %></td>
                               <td><%= label_tag dom_id(issue), issue.issuecode %></td>
                               <td><small><%= label_tag dom_id(issue), issue.name %></small></td>
                               <td><%= issue.status_humanize %></td>

                            <td><%= label_tag dom_id(issue), issue.disputant %></td>

                               <td><%= label_tag dom_id(issue), issue.community %></td>
                            </tr>
                        <% end %>



                        </tbody>
                        </table>

</div>
          </div>

                    </div>



</div>
<% end %>



<script>
    $('#datepicker-meeton').Zebra_DatePicker();
</script>

app/views/meetings/_meetings_admintable.html.erb
<table class="table">
  <thead>
  <tr>
    <th>ID</th>
    <th>Meeting Date</th>
    <th>Time Start</th>

    <th>Structure</th>
    <th>Agenda Issues</th>


  </tr>
  </thead>


  <tbody>
  <% @meetings.each do |meeting| %>

      <% agendaitems = Agenda.where('meeting_id = ?', meeting.id) %>
      <tr>
        <td><%= link_to meeting.meetingid, meeting %></td>
        <td><%= meeting.status %></td>
        <td><%=  meeting.meeting_on.strftime("%m/  %d/%Y") if meeting.meeting_on %></td>
        <td><%=  meeting.starts_at.strftime("%H:%M") if meeting.starts_at %></td>


        <td>
          <% if meeting.structure_id.present? && meeting.structure_id.to_i > 0 %>
              <%= link_to meeting.structure.name, meeting.structure if meeting.structure_id %>
          <% end %>
        </td>

        <td><%= agendaitems.count if agendaitems %></td>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/meetings/_meetings_table.html.erb
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @tabhead %></h3>
    </div>
    <div class="panel-body">

      <!---<table id="meetingstable"  class="hover" cellspacing="0" width="100%">--->


        <table id="meetingstable" class="table table-striped table-hover">
        <thead>
        <tr>
          <th>ID</th>
          <th>Status</th>
          <th>Meeting Date</th>
          <th>Time Start</th>

         <th>Structure</th>
          <th>Agenda Issues</th>


        </tr>
        </thead>


        <tbody>
        <% @meetings.each do |meeting| %>

        <% agendaitems = Agenda.where('meeting_id = ?', meeting.id) %>
            <tr>
              <td><%= link_to meeting.meetingid, meeting %></td>
              <td><%= meeting.status %></td>
              <td><%=  meeting.meeting_on.strftime("%m/  %d/%Y") if meeting.meeting_on %></td>
              <td><%=  meeting.starts_at.strftime("%H:%M") if meeting.starts_at %></td>


                         <td>
                           <% if meeting.structure_id.present? && meeting.structure_id.to_i > 0 %>
                             <%= link_to meeting.structure.name, meeting.structure if meeting.structure_id %>
                               <% end %>
                               </td>

              <td><%= agendaitems.count if agendaitems %></td>

            </tr>
        <% end %>
        </tbody>
      </table>





    </div>
  </div>





  <script>
    $('#meetingstable').dataTable({
      'paging':   true,  // Table pagination
      'ordering': true,  // Column ordering
      'info':     true,  // Bottom left status text
// Text translation options
// Note the required keywords between underscores (e.g _MENU_)
      oLanguage: {
        sSearch:      'Search all columns:',
        sLengthMenu:  '_MENU_ records per page',
        info:         'Showing page _PAGE_ of _PAGES_',
        zeroRecords:  'Nothing found - sorry',
        infoEmpty:    'No records available',
        infoFiltered: '(filtered from _MAX_ total records)'
      }
    });

    $(document).ready(ready);
    $(document).on('page:load', ready);
  </script>

app/views/meetings/_reopenmeeting.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@meeting, multipart: true, remote: false, html: {role: :form, 'data-model' => 'meeting', id: 'close_meeting_form'}) do |f| %>

    <%= hidden_field(:meeting, :meeting_held, :value => false) %>
    <div class="field">
      <%= f.label 'Reopen Meeting Note:' %><br>
      This Note will be saved to the Meeting record. It will override the previous closure note<br>
      <%= f.text_area :reopennote,  cols: "120", rows: "12" %>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', :class => "btn-small btn-primary" %>
    </div>
<% end %>

app/views/meetings/blankforms.pdf.erb
<style>
  div.entry {
      border: solid 3px #666;
      width: 100px;
  }


</style>


<h1>Document Structure Meeting</h1>

<h2>Persons in Attendance</h2>

Total
<div class="entry">






</div>

app/views/meetings/edit.html.erb
<div class="container">

<h3>Editing Meeting</h3>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>
</div>

app/views/meetings/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>


  <h2>Meetings List</h2>
  <div class="pull-right">
    <%#= link_to 'New Meeting', new_meeting_path, :class => "btn btn-primary" %>
  </div>
  <%= render 'meetings_table' %>


</div>

app/views/meetings/new.html.erb
<div class="container">
<h2>New Security Council Meeting</h2>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>
</div>