config/routes.rb
Rails.application.routes.draw do

  resources :infopopups
  resources :metrics
  resources :quarters
  resources :projects
  resources :agendas
  resources :userroles
  resources :actiontypes
  resources :mediators
  resources :mediations
  resources :participations
  resources :managers
  resources :assignments
  resources :roles

  #match 'users_admin/', to: 'users#create', via: :post, as: 'admin_create_user'

  #post 'admin_password_reset', to: 'users#password_reset', as: 'admin_password_reset'
  match '/users_password_reset', to: 'users#password_reset', via: :patch, as: 'admin_password_reset'

  resources :scopes
  resources :memberships
  resources :userroles
  resources :people
  resources :actiontypes
  resources :issueactions
  resources :actions
  resources :communities
  resources :appissues do
    collection { post :uploadcsv }
  end
  resources :structuretypes
  resources :statuses
  resources :categories
  resources :issues

  resources :organizations
  resources :meetings
  resources :counties
  resources :structures
  resources :districts



  #resources :searches

  resources :site_images
  resources :site_documents

  #devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_for :users
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  resources :posts
  resources  :people_structures
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  get 'resetpassword', :to => 'users#newpassword', as: 'resetpassword'
  get 'projectdashboard', :to => 'projects#dashboard', as: 'projectdashboard'
  get 'quarterlyreport', :to => 'projects#quarterlyreport', as: 'quarterlyreport'
  get 'structurereport', :to => 'projects#structurereport', as: 'structurereport'
  get 'projectlofa', :to => 'projects#lofa', as: 'projectlofa'
  get 'projectgrandgedeh', :to => 'projects#grandgedeh', as: 'projectgrandgedeh'
  get 'projectbong', :to => 'projects#bong', as: 'projectbong'
  get 'projectnimba', :to => 'projects#nimba', as: 'projectnimba'
  get 'managersmap', :to => 'structures#managersmap', as: 'managersmap'


  post 'addtoagenda', to: 'issuesactions#create_meetingagenda', as: 'addtoagenda'

  get 'resolution', to: 'issues#resolution', as: 'resolution'

  post 'addnote', to: 'issues#addnote', as: 'addnote'
  post 'addperson', to: 'structures#addperson', as: 'addperson'
  get 'adjustroles', to: 'users#adjustroles', as: 'adjustroles'
  get 'actionreport', to: 'visitors#actionreport', as: 'actionreport'
  get 'qtrreport', to: 'projects#qtrreport', as: 'qtrreport'
  get 'searchissues', to: 'issues#searchissues', as: 'searchissues'
  get 'issueresults', to: 'issues#searchresults', as: 'issueresults'
  get 'fixissue', to: 'appissues#fixissues', as: 'fixissues'

  get 'searchbyqtr', to: 'issues#searchbyqtr', as: 'searchbyqtr'
  get 'searchbyqtrresults', to: 'issues#searchbyqtrresults', as: 'searchbyqtrresults'
  get 'searchmeetings', to: 'meetings#searchmeetings', as: 'searchmeetings'
  
  get 'meetingresults', to: 'meetings#meetingresults', as: 'meetingresults'
  
  get 'monthlyreport', to: 'projects#monthlyreport', as: 'monthlyreport'
  get 'monthlyresults', to: 'projects#monthlyresults', as: 'monthlyresults'

  get 'qprreport', to: 'projects#qprreport', as: 'qprreport'
  get 'qprresults', to: 'projects#qprresults', as: 'qprresults'


  get 'countyadminreport', to: 'projects#countyadminreport', as: 'countyadminreport'
  get 'countyadminresults', to: 'projects#countyadminresults', as: 'countyadminresults'

  get 'newmldluser', to: 'users#newmldluser', as: 'newmldluser'
  post 'createuser', to: 'users#createuser', as: 'createuser'
  get 'deletemanager', to: 'structures#deletemanager', as: 'deletemanager'
  get 'deletemediator', to: 'mediations#deletemediator', as: 'deletemediator'
  get 'deletemembership', to: 'structures#deletemembership', as: 'deletemembership'
  get 'deleteparticipation', to: 'meetings#deleteparticipation', as: 'deleteparticipation'
  get 'deletedisputant', to: 'issues#deletedisputant', as: 'deletedisputant'
  get 'deletecommitteemember', to: 'issues#deletecommitteemember', as: 'deletecommitteemember'

  get 'meettemplate', to: 'meetings#blankmeeting', as: 'meettemplate'
  get 'othercategories', to: 'projects#othercategories', as: 'othercategories'
  get 'resultaudit', to: 'projects#resultaudit', as: 'resultaudit'
  post 'adddisputant', to: 'issues#adddisputant', as: 'adddisputant'
  post 'addcommitteemember', to: 'issues#addcommitteemember', as: 'addcommitteemember'
  post 'addparticipant', to: 'meetings#addparticipant', as: 'addparticipant'
  post 'addmediator', to: 'mediations#addmediator', as: 'addmediator'
  post 'addmemember', to: 'structures#addmembership', as: 'addmember'
  post 'addmanager', to: 'structures#addmanager', as: 'addmanager'
  get 'seedpeeps', to: 'people#seedpeeps', as: 'seedpeeps'
  get 'datacsv', to: 'issues#dumpfile', as: 'datacsv'
  get 'issuedump', to: 'issues#issuedump', as: 'issuedump'
  get 'structureissuedump', to: 'structures#structureissuedump', as: 'structureissuedump'

  get 'meetingcheck', to: 'meetings#meetingchecker', as: 'meetingcheck'
  get 'basicdata', to: 'projects#basicdatasetup', as: 'basicdata'
  get 'basictableoutput', to: 'projects#basictableoutput', as: 'basictableoutput'
  get 'downloadissues', to: 'issues#action_name', as: 'downloadissues'
  get 'seeder', to: 'issues#seeder', as: 'seeder'
  get 'clearsteve', to: 'projects#clearsteve', as: 'clearsteve'
  get '/tests2', :to => redirect('/tests2.html')
  root 'visitors#index'
  #get "counties/:county_id/districts", to: "application#districts", as: "districts", format: :json



end

app/models/county.rb
class County < ActiveRecord::Base
  has_many :structures
  has_many :districts
end

app/models/issue.rb
class Issue < ActiveRecord::Base

  validates :name, presence: true
  validates :structure_id, presence: true
  validates :district_id, presence: true
  validates :community, presence: true


  belongs_to :structure
  belongs_to :district
  belongs_to :person, :foreign_key => :raised_by
  belongs_to :user, :foreign_key => :created_by
  belongs_to :category
  belongs_to :scope
  belongs_to :resolutiontype

  extend EnumerateIt
  has_enumeration_for :status


  has_many :issues_districts, :dependent => :destroy
  has_many :districts, :through => :issues_districts



  has_many :committeemembers, :dependent => :destroy
  has_many :memberships, :through => :committeemembers


  has_many :disputants, :dependent => :destroy
  has_many :people, :through => :disputants

  has_many :agendas, :dependent => :destroy
  has_many :meetings, :through => :agendas

  has_many :actionstructures

  has_many :issueactions, :dependent => :destroy
  has_many :users, :through => :issueactions

  has_many :site_documents

  has_many :mediations



  def issuecode()
    short = self.structure.short

    issueid = (short + '-'  + self.id.to_s)
    return issueid

  end

  def issuestatus(status)

    if status == Status::ONGOING
      vclass='ongoing'
    elsif status == Status::RESOLVED
      vclass='resolved'
    elsif status == Status::CANCELLED
      vclass='cancelled'
    elsif status == Status::MEDIATION
      vclass='mediation'
    elsif status == Status::NEW
      vclass='new'
    else
      vclass = 'default'
    end
    return vclass
  end


  def onagenda(meeting_id)

     findagenda = Issueaction.where('issue_id = ? and meeting_id = ? and actiontype = ?', self.id, meeting_id, Actiontype::AGENDA)

    if findagenda.count > 0
    return true
    else
      return false
    end

  end

  def resolved_year
  end

  def openmediation
    mediationchk = Mediation.where('issue_id =? and mediate_end is NULL', self.id).count

      return mediationchk

  end

=begin
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |issue|
        csv << issue.attributes.values_at(*column_names)
      end
    end
  end
=end

  def xlscategory(categoryid)

    if !categoryid.nil?
      qresult = Category.find(categoryid)
      return qresult.name
    else
      return 'na'
    end
  end

  def xlsdistrict(districtid)
    if !districtid.nil?
      qresult = District.find(districtid)

      return qresult.name
    else
      return 'na'
    end
  end




























end

app/models/issueaction.rb
class Issueaction < ActiveRecord::Base
  belongs_to :issue
  belongs_to :meeting
  belongs_to :user
  belongs_to :structure
  belongs_to :mediation

  extend EnumerateIt
  has_enumeration_for :actiontype, create_helpers: true



  def actiondesc(action)



    if action == Actiontype::CREATED
      str = 'New Issue Created'

    elsif action == Actiontype::AGENDA
      str = 'Issue on Agenda'

    elsif action == Actiontype::COMMENT
      str = 'Comment added'
    elsif action == Actiontype::ONGOING
      str = 'Issue not resolved'
    elsif action == Actiontype::RESOLVED
      str = 'Issue Resolved'
    elsif action == Actiontype::ESCALATED
      str = 'Issue Referred Up'
    elsif action == Actiontype::MEDIATION
      str = 'Send to Mediation'
    elsif action == Actiontype::CANCELLED
      str = 'Issue Cancelled'
    elsif action == Actiontype::REOPENED
      str = 'Issue Now Reopened'
    else
      str = ''
    end
    return str






  end











  def resolutiontype_id
  end




  def resolution
  end

  def resolution_date
  end

end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_addcommitteemember.html.erb
<%= form_tag addcommitteemember_path do %>


    <div class="field" id="e2">




      <small>Select/Search Person</small><br>
      <select name="membership_id" class="chosen-select">
        <option value = "">Select -></option>

        <% @available_members.each do |m| %>

            <option value="<%= m.id %>"><%= m.person.fullname %></option>
        <% end %>
      </select>





    </div>


    <br><br>





    <%= hidden_field_tag(:issue_id, @issue.id) %>
    <div class="actions">
      <%= submit_tag 'Submit', :class => "btn btn-small btn-primary" %>
    </div>
<% end %>


<script type="text/javascript">
    var config = {
        '.chosen-select'           : {},
        '.chosen-select-deselect'  : {allow_single_deselect:true},
        '.chosen-select-no-single' : {disable_search_threshold:10},
        '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
        '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
        $(selector).chosen(config[selector]);
    }
</script>

app/views/issues/_adddisputant.html.erb
<%= form_tag adddisputant_path do %>

    <%= render 'people/addpeopletoobject' %>

    <%= hidden_field_tag(:issue_id, @issue.id) %>
    <div class="actions">
      <%= submit_tag 'Submit', :class => "btn btn-small btn-primary" %>
    </div>
<% end %>

app/views/issues/_addnote.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@issueaction, multipart: true, remote: false, html: {role: :form, 'data-model' => 'issueaction', id: 'comment_form'}) do |f| %>

    <%= hidden_field(:issueaction, :issue_id, :value => @issue.id) %>
    <%= hidden_field(:issueaction, :structure_id, :value => @issue.structure_id) %>
    <%= hidden_field_tag(:fromissue, true) %>
    <%= hidden_field(:issueaction, :actiontype, :value => Actiontype::COMMENT) %>

<%# Added Bootstrap classes, and help-block container for error messages %>
    <div class="field">
      <%= f.label 'Note:' %><br>

      <%= f.text_area :actionbody,  cols: "120", rows: "12" %><br>
      This Note will be saved in the Issue history table.
    </div>
    <div class="actions">
      <%= f.submit 'Submit', :class => "btn-small btn-primary" %>
    </div>
<% end %>

app/views/issues/_escalate.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@issueaction, multipart: true, remote: false, html: {role: :form, 'data-model' => 'issueaction', id: 'new_note_form'}) do |f| %>

    <%= hidden_field(:issueaction, :issue_id, :value => @issue.id) %>
    <%= hidden_field(:issueaction, :structure_id, :value => @issue.structure_id) %>
    <%= hidden_field(:issueaction, :parent_id, :value => @issue.structure.parent_id) %>
    <%= hidden_field_tag(:fromissue, true) %>
    <%= hidden_field(:issueaction, :actiontype, :value => Actiontype::ESCALATED) %>


<%# Added Bootstrap classes, and help-block container for error messages %>
    <div class="field">
      <%= f.label 'Action Note (optional):' %><br>

      <%= f.text_area :actionbody,  cols: "120", rows: "12" %>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', :class => "btn-small btn-primary" %>
    </div>
<% end %>

app/views/issues/_googledata.html.erb
<div class="panel panel-info">

  <div class="panel-heading">
    <h3 class="panel-title">Data Migrated from Google Apps </h3>
  </div>



  <div class="panel-body">



    <table id="googledata"  class="table" cellspacing="0" width="100%">
      

      <tbody>
      <% @gapps.each do |ga| %>
       


<tr><td>TimeStamp</td><td><%= ga.originaltimestamp %></td></tr>
<tr><td>Issue ID</td><td><%= ga.issueid %></td></tr>
<tr><td>UUID</td><td><%= ga.uuid %></td></tr>
<tr><td>Issue Desc</td><td><%= ga.issuedescription %></td></tr>
<tr><td>Issue Name</td><td><%= ga.issuename %></td></tr>
<tr><td>Issue Notes</td><td><%= ga.issuenotes %></td></tr>
<tr><td>Status Notes</td><td><%= ga.statusnotes %></td></tr>
<tr><td>Original User</td><td><%= ga.yourname %></td></tr>
<tr><td>Original Meet Date</td><td><%= ga.originalmeetingdate %></td></tr>
<tr><td>Meeting Code</td><td><%= ga.meetingcode %></td></tr>
<tr><td>Meeting Name</td><td><%= ga.meetingname %></td></tr>
<tr><td>Structure</td><td><%= ga.structure %></td></tr>
<tr><td>Structure County</td><td><%= ga.structurecounty %></td></tr>
<tr><td>Structure District</td><td><%= ga.structuredistrict %></td></tr>
<tr><td>Status</td><td><%= ga.status %></td></tr>
<tr><td>Issue District</td><td><%= ga.issuedistrict %></td></tr>
<tr><td>Issue Community</td><td><%= ga.community %></td></tr>
<tr><td>Category</td><td><%= ga.category %></td></tr>
<tr><td>Raised By</td><td><%= ga.raisedby %></td></tr>
<tr><td>Disputant</td><td><%= ga.disputant %></td></tr>
<tr><td>Duration (days)</td><td><%= ga.duration %></td></tr>
<tr><td>Action Plan Committee</td><td><%= ga.actionplancommittee %></td></tr>
<tr><td>Action Plan Desc</td><td><%= ga.actionplandescription %></td></tr>
<tr><td>ACtion Plan Notes</td><td><%= ga.actionplannotes %></td></tr>
<tr><td>Ongoing/Resolved</td><td><%= ga.ongoing_resolved %></td></tr>
<tr><td>Report Ongoing</td><td><%= ga.report_ongoing %></td></tr>
<tr><td>Resolution Date</td><td><%= ga.resolutiondate %></td></tr>
<tr><td>Resolution Type</td><td><%= ga.resolutiontype %></td></tr>

<tr><td>Resolution</td><td><%= ga.resolution %></td></tr>
<tr><td>Update Type</td><td><%= ga.updatetype %></td></tr>

<tr><td>Update Date</td><td><%= ga.updatedate %></td></tr>
<tr><td>Update Desc</td><td><%= ga.updatedescription %></td></tr>
<tr><td>Mediation Date</td><td><%= ga.mediationdate %></td></tr>
<tr><td>Mediation Outcome</td><td><%= ga.mediationoutcome %></td></tr>

<tr><td>Referral Date</td><td><%= ga.referraldate %></td></tr>
<tr><td>Referred To</td><td><%= ga.referredto %></td></tr>
<tr><td>Referral Note</td><td><%= ga.referralnote %></td></tr>


      <% end %>
      </tbody>
    </table>



  </div>
</div>

app/views/issues/_issues_table.html.erb
<div class="panel panel-info">

  <div class="panel-heading">
    <% if !@metric.nil? %>
        <h3 class="panel-title"><%= @metric.name %> - <%= @d2.year %> <%= @quarter.qtrname(@d2.month) %></h3>
        <%= @resultcount %> Issues
        <% else %>
        <%= @tabhead if @tabhead %>
     <% end %>
  </div>



  <div class="panel-body">



  <table id="issuestable"  class="table table-striped table-hover">
  <thead>
  <tr>
    <th width="60px">ID</th>

    <th>Status</th>
    <th>Name</th>
     <th>Category</th>

    <th>District</th>
    <th>Disputants</th>
    <th>Created</th>


  </tr>
  </thead>
  <tbody>
  <% @issues.each do |issue| %>
  <% statusbox1 = 'btn btn-'+issue.issuestatus(issue.status) %>
  <% mydisputants = Disputant.where(:issue_id => issue.id) %>
      <tr>
        <td><%= link_to issue.issuecode, issue %></td>

        <td><button class="tabstatusbox <%= statusbox1 %>"><%= issue.status_humanize %></button></td>
        <td><%= issue.name %></td>

        <td><%= issue.category.name if !issue.category_id.nil? %></td>
        <td><%= issue.district.name if issue.district_id %></td>
        <td><%= issue.disputant %><br>


          <% mydisputants.each do |d| %>
          <%= d.person.fullname %><br>
          <% end %>

        </td>
        <td><%= issue.created_at.strftime("%m/  %d/%Y") %></td>


      </tr>
  <% end %>
  </tbody>
</table>



  </div>
</div>





<script>


    $('#issuestable').dataTable({
      'paging':   true,  // Table pagination
      'ordering': true,  // Column ordering
      'info':     true,  // Bottom left status text
// Text translation options
// Note the required keywords between underscores (e.g _MENU_)
      oLanguage: {
        sSearch:      'Search all columns:',
        sLengthMenu:  '_MENU_ records per page',
        info:         'Showing page _PAGE_ of _PAGES_',
        zeroRecords:  'Nothing found - sorry',
        infoEmpty:    'No records available',
        infoFiltered: '(filtered from _MAX_ total records)'
      }
    });


  $(document).ready(ready);
  $(document).on('page:load', ready);

</script>

app/views/issues/_mediation.html.erb
<style>
    .notefield {
width: 100%;
}
    </style>

<%= simple_form_for @issueaction, html: { name: "mpop", id: "mpop" } do |f| %>
    <%= hidden_field(:issueaction, :issue_id, :value => @issue.id) %>
    <%= hidden_field_tag(:fromissue, true) %>
    <%= hidden_field(:issueaction, :actiontype,  :value => Actiontype::MEDIATION) %>

    <div class="field">

      <%= f.label 'Mediation Note (optional):' %><br>
      <%= f.input :actionbody, class: "notefield", rows: "12", label: false %>
    </div>



    <div class="form-group">
      <%= f.label 'Mediation Start (required)', :class => "col-sm-2 control-label" %>
      <div class="col-sm-10" id="sandbox-container">
        <div class="input-group date">

          <input  name="mediate_start" type="text" id="mediatestart" required >
          <%# f.input :mediation_start, :class => "form-control", :width => "80" %>
        </div>

      </div>

    </div>
<br>
    <br>
    <div class="actions">
      <%= f.submit 'Submit', :class => "btn-small btn-primary" %>
    </div>
<% end %>


<script>
    $('#mpop').parsley();
    $('#mediatestart').Zebra_DatePicker();

</script>

app/views/issues/_resolution.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>


<%= form_for(@issueaction, multipart: true, remote: false, :novalidate => "", html: {role: :form,  name: "resolvepop", 'data-model' => 'issueaction', id: 'resolvepop'}) do |f| %>
    <% if @issueaction.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

          <ul>
            <% @issue.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= hidden_field(:issueaction, :issue_id, :value => @issue.id) %>
    <%= hidden_field_tag(:fromissue, true) %>
    <%= hidden_field(:issueaction, :actiontype, :value =>  Actiontype::RESOLVED) %>


<%# Added Bootstrap classes, and help-block container for error messages %>
    <div class="field">
      <%= f.label 'Note:' %><br>
      <%= f.text_area :actionbody,  cols: "120", rows: "2" %><br>
      This Note will be saved in the Issue history table.
    </div>
<hr>
    <div class="form-group">
      <%= f.label 'Resolution Date', :class => "col-sm-2 control-label" %>
      <div class="col-sm-10" id="sandbox-container">
        <div class="input-group date">
          <input  name="resolution_date" type="text" id="datepicker-resolvedate" class="form-control" width="80" required >
          <%# f.input :mediation_start, :class => "form-control", :width => "80" %>
        </div>

      </div>

    </div>

<br><br>




    <div class="form-group">
      <%= f.label :resolutiontype, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">

        <%#= f.collection_select(:resolutiontype_id, Resolutiontype.all, :id, :name, {:required => true, :class => "form-control"}) %>
        <%= f.collection_select :resolutiontype_id, Resolutiontype.all, :id, :name, {}, {required: true, class: "form-control", style: "width: 250px"} %>

      </div>
    </div>







    <div class="form-group">
      <%= f.label 'Resolution Description', :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :resolution, :id => "descedit", :cols => "100", :rows => "10", required: true  %>

      </div>
    </div>






    <div class="actions">
      <%= f.submit 'Submit', :class => "btn-small btn-primary" %>
    </div>
<% end %>

<script>
    $('#resolvepop').parsley();
    $('#datepicker-resolvedate').Zebra_DatePicker();

</script>

app/views/issues/edit.html.erb
<div class="container">

<h3>Editing Issue</h3>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>
</div>

app/views/issues/searchbyqtr.html.erb
<style>
    .chkpanel {
        font-size: 14px;
        font-weight: normal;


    }



</style>
<script>
    $(document).ready(function() { $("#issuedisputants").select2(); });
</script>






<div class="container">
  <div class="col-sm-4">

  <h2>Search Issues</h2>
  <div class="row">
    <%= form_tag searchbyqtrresults_path, :method => :get do %>





        <h4>Select Quarter</h4><br>
        <select name="quarter_id" class="input-md form-control">
          <option value = "">Select -></option>
          <% Quarter.all.each do |q| %>
              <option value="<%= q.id %>"><%= q.q1234(q.qtrmonth,q.qtryear) %></option>
          <% end %>
        </select>





        <%#= select_tag(:category_ids, Category.all, :id, :name) {:include_blank => "Select"}, { :multiple => true })%><br><br>
        <div class="field">
          <h4>Filter Issues</h4>
          <%= select_tag "code", options_from_collection_for_select(Metric.all, "code", "name"), :include_blank => "Select", :multiple => false  %>
        </div>



        <%#= select_tag(:category_ids, Category.all, :id, :name) {:include_blank => "Select"}, { :multiple => true })%><br><br>
        <div class="field">
          <h4>Select Structure</h4>
          <%= select_tag "structure_ids", options_from_collection_for_select(Structure.all, "id", "name"), :include_blank => "Select", :multiple => true  %>
        </div>



        <hr>
          <div class="actions">
            <%= submit_tag 'Search', :class => "btn btn-primary" %>
          </div>
          <br><BR>    <div class="actions">
          <%= button_tag "Reset", type: :reset, :class => 'btn btn-default' %>
        </div>
        </div>
    <% end %>

  </div>









</div>

app/views/issues/searchissues.html.erb
<style>
    .chkpanel {
        font-size: 14px;
        font-weight: normal;


    }



</style>
<script>
   /* $(document).ready(function() { $("#issuedisputants").select2(); });*/
</script>






<div class="container">


<h2>Search Issues</h2>

  <%= form_tag issueresults_path, :method => :get do %>

  <div class="row">

    <div class = "col-sm-4">
      <h4>MLDL Structures</h4>
      <div class="chkpanel">

        <% @allstructures.each do |item| %>


            <% if item.structuretype == Structuretype::NSC %>
                <strong>  <%= check_box_tag "structure_ids[]", item.id %><%= item.name %><br><br></strong>
            <% elsif item.structuretype ==  Structuretype::CSC %>
                <strong>  <%= check_box_tag "structure_ids[]", item.id %><%= item.name %><br></strong>
            <% elsif item.structuretype ==  Structuretype::DSC  %>

                &nbsp;&nbsp;&nbsp;&nbsp;  <%= check_box_tag "structure_ids[]", item.id %><%= item.name %><br>
            <% elsif item.structuretype ==  Structuretype::CF  %>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>  <%= check_box_tag "structure_ids[]", item.id %><%= item.name %><br></em>
            <% end %>


        <% end %>
      </div>

    </div>



    <div class = "col-sm-4">

      <h4>Search String</h4>
      <div class="field">
            <%= text_field_tag 'search_term' %><br>
                <small>Community names, Issue names descriptions, Action comments, resolutions</small>
      </div>

      <div class="field">

          <h4>Issue Status</h4>
        <strong><span style="color: red">Defaut is "Ongoing"</span></strong><br>
          <select name="status" class = "form-control">
            <option value="1">New</option>
            <option value="2" selected="selected">Ongoing</option>
            <option value="3">Resolved</option>
            <option value="4">Mediation</option>
            <option value="5">Cancelled</option>
          </select>
      </div>


      <div class="field">
        <h4>Categories</h4>
        <%= select_tag "category_ids", options_from_collection_for_select(Category.all, "id", "name"), :include_blank => "Select", :multiple => true  %>
      </div>


      <div class="field">
        <h4>Districts <small>(where Issue Occured)</small></h4>
        <%= select_tag "district_ids", options_from_collection_for_select(District.all, "id", "name"), :include_blank => "Select", :multiple => true  %>
      </div>

    </div>



    <div class="col-sm-4">



      <div class="field">
        <h4>Select/Search Old Issue Ids</h4><br>
        <small>Note: Hypens removed to allow select search</small>
        <select name="old_id" class="chosen-select">
          <option value = "">Select -></option>
          <% @alloldids.each do |issue| %>

              <option value="<%= issue.id %>"><%= issue.uuid.tr("-", " ") %></option>
          <% end %>
        </select>



      </div>

      <div class="field">



        <h4>Select/Search New Issue IDs</h4><br>
        <small>Note: Hypens removed to allow select search</small>
        <select name="new_id" class="chosen-select">
          <option value = "">Select -></option>
          <% @allnewids.each do |issue2| %>

              <option value="<%= issue2.id %>"><%= issue2.issuecode.tr("-"," ") %></option>
          <% end %>
        </select>
  </div>



      <br><br>


      <div class="field">



        <h4>Select/Search Disputants</h4><br>
        <select name="person_id" class="chosen-select input-md form-control">
          <option value = "">Select -></option>
          <% @alldisputants.each do |disp| %>

              <option value="<%= disp.person_id %>"><%= disp.person.fullname %></option>
          <% end %>
        </select>
      </div>


      <div class="actions">
        <%= submit_tag 'Search', :class => "btn btn-primary" %>
      </div>
      <br><BR>    <div class="actions">
      <%= button_tag "Reset", type: :reset, :class => 'btn btn-default' %>
    </div>
    </div>



</div>
  <% end %>
</div>



<script>

    ready = function(){


        var config = {
            '.chosen-select'           : {},
            '.chosen-select-deselect'  : {allow_single_deselect:true},
            '.chosen-select-no-single' : {disable_search_threshold:10},
            '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
            '.chosen-select-width'     : {width:"95%"}
        }
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }






    };
    $(document).ready(ready);
    $(document).on('page:load', ready);

</script>